credentials:
  usernames:
    saksham:
      email: saksham@gmail.com
      name: Saksham
      password: "$2b$12$7gU8mfWqOLe3r51F5B/YiecU8mLy6XFNLe3YyoP9lT8FK1Yxti7gS"  

cookie:
  expiry_days: 7
  key: 8dj38djs82js92ksj2
  name: medical_chatbot_cookie

preauthorized:
  emails:
    - saksham@gmail.com